# Generated by Django 4.2.7 on 2024-01-11 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id_cities', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_countries', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id_facilities', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructures',
            fields=[
                ('id_infrastructures', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id_reservationstatus', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='SportCenters',
            fields=[
                ('id_sportcenters', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('id_cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id_sports', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='SportZones',
            fields=[
                ('id_sportzones', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=35)),
                ('id_cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.cities')),
                ('id_facilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.facilities')),
                ('id_infrastructures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.infrastructures')),
                ('id_sportcenters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.sportcenters')),
                ('id_sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.sports')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id_states', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('id_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.countries')),
            ],
        ),
        migrations.CreateModel(
            name='SportZonesPhotos',
            fields=[
                ('id_photos', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_sportzones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.sportzones')),
            ],
        ),
        migrations.CreateModel(
            name='SportCentersPhotos',
            fields=[
                ('id_photos', models.AutoField(primary_key=True, serialize=False)),
                ('url_image', models.ImageField(default='images/transparent.png', upload_to='images/sport-centers/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('id_sportcenters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.sportcenters')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id_reservations', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('started', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_admistrators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.logentry')),
                ('id_reservationstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.reservationstatus')),
                ('id_sportzones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.sportzones')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_clients', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=35)),
                ('id_auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='id_states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.states'),
        ),
    ]
