# Generated by Django 5.0.1 on 2024-01-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportzones',
            name='id_cities',
        ),
    ]
