# Generated by Django 5.0.1 on 2024-01-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0002_remove_sportzones_id_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportzonesphotos',
            name='url_image',
            field=models.ImageField(default='images/transparent.png', upload_to='images/sport-zones/'),
        ),
    ]
