# Generated by Django 5.0.1 on 2024-01-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0004_sportcenters_url_image_sportzones_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
    ]
