# Generated by Django 5.0.1 on 2024-01-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0006_remove_reservations_id_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id_clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservacion.clients'),
        ),
    ]
