# Generated by Django 5.0.1 on 2024-02-17 04:21

import Reservacion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0007_alter_reservations_id_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='contact_number',
            field=Reservacion.models.PhoneNumberField(default='', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='El número de teléfono debe tener un formato válido.')]),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default='', max_length=180),
        ),
    ]
