# Generated by Django 5.0.2 on 2024-02-18 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0008_clients_contact_number_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='finished',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='id_reservationstatus',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Reservacion.reservationstatus'),
        ),
    ]
