# Generated by Django 5.0.2 on 2024-02-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0009_alter_reservations_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportzones',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
