# Generated by Django 5.0.2 on 2024-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0010_sportzones_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportzones',
            name='section',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
