# Generated by Django 5.0.2 on 2024-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0011_alter_sportzones_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcenters',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sportzones',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
