# Generated by Django 5.0.2 on 2024-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0012_alter_sportcenters_name_alter_sportzones_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
