# Generated by Django 5.0.2 on 2024-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservacion', '0013_reservations_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
